package cn.hsa.module.insure.module.entity;

import cn.hsa.base.PageDO;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.format.annotation.DateTimeFormat;

import java.io.Serializable;
import java.util.Date;

/**
 * @Package_name:cn.hsa.module.insure.module.entity
 * @Class_name:.InsureDoctorInfoDO
 * @Describe:医保上传医师基本信息
 * @Author: JiGuang.liao
 * @Email: jiguang.liao@powersi.com.cn
 * @Date: 2021-09-13
 * @Company: CopyRight@2021 POWERSI Inc.All Rights Reserverd
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)
public class InsureDoctorInfoDO extends PageDO implements Serializable {
        /** 版本号 */
        private static final long serialVersionUID = 5990977220686758238L;

        /* This code was generated by TableGo tools, mark 1 begin. */

        /** 主键ID */
        private String id;

        /** 医院编码 */
        private String hospCode;

        /** 医保编码 */
        private String insureRegCode;

        /** 医师编码 */
        private String drCodg;

        /** 医师姓名 */
        private String drName;

        /** 执业医师编号 */
        private String pracDrId;

        /** 医师执业类型 */
        private String drPracType;

        /** 医师专业技术职务 */
        private String drProTechDuty;

        /** 医师执业范围代码 */
        private String drPracScpCode;

        /** 专业编号 */
        private String proCode;

        /** 是否申报为本市专家库成员 */
        private String dclProfFlag;

        /** 医师执业情况 */
        private String practiceCode;

        /** 医师职称编号 */
        private String drProfttlCode;

        /** 个人能力简介 */
        private String psnItro;

        /** 多点执业标志 */
        private String mulPracFlag;

        /** 主执业机构标志 */
        private String mainPracinsFlag;

        /** 医院科室编码 */
        private String hospDeptCode;

        /** 定岗标志 */
        private String bindFlag;

        /** 是否医保专家库成员 */
        private String siprofFlag;

        /** 是否本地申报专家 */
        private String loclprofFlag;

        /** 是否医保医师 */
        private String hiDrFlag;

        /** 证件类型 */
        private String certType;

        /** 证件号码 */
        private String certno;

        /** 备注 */
        private String memo;

        /** 是否上传 */
        private String isUpload;

        /** 创建者id */
        private String crteId;

        /** 创建者名称 */
        private String crteName;

        /** 创建时间 */
        @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
        @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
        private Date crteTime;
}