package cn.hsa.module.insure.module.entity;

import cn.hsa.base.PageDO;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.format.annotation.DateTimeFormat;

import java.io.Serializable;
import java.util.Date;

/**
 * @Package_name:cn.hsa.module.insure.module.entity
 * @Class_name:.InsureDoctorInfoDO
 * @Describe:医保上传医师基本信息
 * @Author: JiGuang.liao
 * @Email: jiguang.liao@powersi.com.cn
 * @Date: 2021-09-13
 * @Company: CopyRight@2021 POWERSI Inc.All Rights Reserverd
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)
public class InsureDoctorMgtinfoDO extends PageDO implements Serializable {
        /** 版本号 */
        private static final long serialVersionUID = 7461918484889673964L;

        /* This code was generated by TableGo tools, mark 1 begin. */

        /** 主键ID */
        private String id;

        /** 医院编码 */
        private String hospCode;

        /** 医保编码 */
        private String insureRegCode;

        /** 医保上传医生信息表id */
        private String insureDoctorId;

        /** 医师编码 */
        private String drCodg;

        /** 医疗服务类型 */
        private String hiServType;

        /** 医疗服务类型名称 */
        private String hiServName;

        /** 服务状态0；正常  1：暂停 */
        private String hiServStas;

        /** 医疗服务开始时间 */
        @JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8")
        @DateTimeFormat(pattern = "yyyy-MM-dd")
        private Date begndate;

        /** 医疗服务结束时间 */
        @JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8")
        @DateTimeFormat(pattern = "yyyy-MM-dd")
        private Date enddate;

        /** 备注 */
        private String memo;

        /** 创建人ID */
        private String crteId;

        /** 创建人ID */
        private String crteName;

        /** 创建时间 */
        @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
        @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
        private Date crteTime;
}