FROM java:8
RUN groupadd --gid 5000 app &&  useradd --home-dir /home/app --create-home --uid 5000 --gid 5000  app
USER app
WORKDIR /
ADD /xxl-job-executor.jar /
ENTRYPOINT ["java","-XX:+UseG1GC","-jar","/xxl-job-executor.jar"]
