version: '3'
services:
  # nacos-server服务注册与发现，配置中心服务
  hsa-center:
    image: image-hsa-platform:1.0
    container_name: cont-hsa-platform
    ports:
      - "9992:9992"
      - "7000:7000"
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
      - spring.main.allow-bean-definition-overriding=true
      - spring.cloud.nacos.config.server-addr=nginx:8848
      - spring.cloud.nacos.config.enabled=true
      - dubbo.registry.address=nacos://nginx:8848
      - -Dfile.encoding=UTF-8
      - -Dsun.jnu.encoding=UTF-8
    networks:
      - custom_net
    volumes:
      - /etc/localtime:/etc/localtime
      - /app/log/:/logs/

networks:
  custom_net:
    external:
      name: app_net
