version: '3'
services:   
# 库存管理
  hsa-stro:
    image: image-hsa-stro:1.0
    container_name: cont-hsa-stro
    ports:
      - "9007:9007"
      - "29007:29007"
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
      - spring.cloud.nacos.config.server-addr=nginx:8848
      - spring.cloud.nacos.config.enabled=true
      - dubbo.registry.address=nacos://nginx:8848
    networks:
      - custom_net
    volumes:
      - /etc/localtime:/etc/localtime
      - /app/log/:/logs/      

networks:
  custom_net:
    external:
      name: app_net
