version: '3'
services:   
# 系统管理
  hsa-sys:
    image: image-hsa-sys:1.0
    container_name: cont-hsa-sys
    ports:
      - "9003:9003"
      - "29003:29003"
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
      - spring.cloud.nacos.config.server-addr=nginx:8848
      - spring.cloud.nacos.config.enabled=true
      - dubbo.registry.address=nacos://nginx:8848
    networks:
      - custom_net
    volumes:
      - /etc/localtime:/etc/localtime
      - /app/log/:/logs/      
    logging:
      driver: "json-file"
      options:
        max-size: "1g"

networks:
  custom_net:
    external:
      name: app_net

