version: '3'
services: 
# 入出院启动函数
  hsa-report:
    image: image-hsa-report:1.0
    container_name: cont-hsa-report
    ports:
      - "9015:9015"
      - "29015:29015"
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
      - spring.cloud.nacos.config.server-addr=nginx:8848
      - spring.cloud.nacos.config.enabled=true
      - dubbo.registry.address=nacos://nginx:8848
    networks:
      - custom_net
    volumes:
      - /etc/localtime:/etc/localtime
      - /app/log/:/logs/
      - /app/project/powersiReport:/app/project/powersiReport
      - /app/nginx:/app/nginx

networks:
  custom_net:
    external:
      name: app_net
