test:
  name: xiangtao1
logging:
  file:
    path: /tsf-demo-logs

swagger:
  enabled: true
spring:
  autoconfigure:
    exclude: com.tencent.tsf.swagger.autoconfig.TsfSwaggerAutoConfiguration

cache:
  cluster0:
    cacheName: hsaf-redis
    password: onfvUGNpwgPExtThe3uZ9mBiH0IDjk7QASFO4qY6JcslX2KW
    nodes: 172.17.28.14:2075,172.17.28.15:4414,172.17.28.16:1725

mybatis:
  database:
    provider:
      type: mysql
    pageHelper:
      dialect: mysql
db:
  druid:
    url: jdbc:mysql://172.17.27.16:15068/demo?connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    driverClassName: com.mysql.jdbc.Driver
    username: template
    password: template@123
    validationQuery: SELECT 'x'

fsstore:
  url: http://172.17.20.126:8080/regioss78a0c1f2
  bucket: regioss78a0c1f2
cos:
  endpoint: http://172.17.27.201:8080
  accessKey: HLGUQYMTZ97VIO0WJ1P3
  secretKey: M3zoMEYdXnuwLHtxIQC5JsvzoCW8f46s1h5IgI54

gateway:
  csb:
    csburl: http://39.106.64.95:8086/CSB
    accessKey: 3ac22a8c0644460b86eebe0b8bf162b8
    securityKey: ic1m+47vSRKddKdXjSgUn/ZF/7A=
    connectionMax: 200
    connectionTimeout: 2000
    connectionSoTimeout: 2000
    connectionCrTimeout: 2000
    skipConnectionPool: false
    connectionAsync: false
  tencent:
    gatewayUrl: http://demo.rio.tencent.com/ebus
    paasid: testapp1_passid
    token: DC8d9v0U3XgnuNR73XgRPtGcDz3badZs
    socketTimeout: 2000
    connectTimeout: 2000
    soTimeout: 2000
    connectionRequestTimeout: 2000
    maxConnTotal: 10
    maxConnPerRoute: 3
  generic:
    gatewayUrl: http://127.0.0.1:8000
    apikey: test123
    socketTimeout: 2000
    connectTimeout: 2000
    soTimeout: 2000
    connectionRequestTimeout: 2000
    maxConnTotal: 10
    maxConnPerRoute: 3

idgenerator:
  common:
    step: 1000
  redis:
    clusterNodes: 172.17.28.14:3333,172.17.28.15:1955,172.17.28.16:3555
    password: l34woVKkWiBT6p920SvDnIgMcsu1AhzePfyaCUZdG7tExOjN

xxl:
  job:
    enabled: true
    admin:
      addresses: http://192.168.6.7:8080/xxl-job-admin
    accessToken:
    executor:
      appname: hsa-xxx
      ip:
      port: 9998
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: -1

mq:
  tencent:
    NAME_SERVER_ADDRESS: http://172.17.25.29
    SECRET_ID: 100000000
    SECRET_KEY: 10000000
    SIGN_METHOD: HmacSHA256
    REQUEST_TIMEOUT_MS: 5000
    RETRY_TIMES_WHEN_SEND_FAILED: 3
    PULL_WAIT_SECONDS: 1
  topic:
    string: MQ_QUEUE_HSA_TEMPLATE_DEV
    dto: MQ_HSA_CZHY_DEMO_DTO

server:
  servlet:
    session:
      cookie:
        path: /

session:
  redis:
    cluster:
      nodes: 172.17.28.14:4202,172.17.28.15:4246,172.17.28.16:1945
    password: 3D2ShVk76zoj8Ad15nWgMeX9s4avyTqKJQilpfwCLZRbBYHm
    database: 0
    timeout: 30000
    pool:
      maxIdle: 5
      maxTotal: 10
      maxWaitMillis: 5000
      testOnBorrow: false
      testOnReturn: false
security:
  type: hsa-mock
  oauth2:
    client:
      access-token-uri: http://127.0.0.1:7001/uaa/oauth/token
      user-authorization-uri: http://127.0.0.1:7001/uaa/oauth/authorize
      client-id: acme1
      client-secret: acmesecret1
      client-authentication-scheme: header
    resource:
      jwt:
        key-value: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB

upengine:
  sdk:
    urlPrefix: http://172.17.24.1:8080/up-runtime-server/service/rest/
    clientType: ten
    tenantCode: C2D1T1
    accessUser: AUC2D1T1
    checkCode: C2D1T1123456
    area: .*
    connectTimeout: 1000
    readTimeout: 30000
    charset: UTF-8