FROM java:8
RUN groupadd --gid 5000 app &&  useradd --home-dir /home/app --create-home --uid 5000 --gid 5000  app
USER app
WORKDIR /
ADD /hsa-report.jar /
ENTRYPOINT ["java",,"-Xms1024m","-Xmx2048m","-XX:+UseG1GC","-XX:+HeapDumpOnOutOfMemoryError","-XX:HeapDumpPath=/logs/hsa-report","-XX:+PrintGCDetails", "-XX:+PrintGCTimeStamps", "-XX:+UseGCLogFileRotation", "-XX:NumberOfGCLogFiles=10", "-XX:GCLogFileSize=10M", "-Xloggc:/logs/hsa-report/gc.log","-jar","/hsa-report.jar"]
